### PR TITLE
[api] Add GuID

### PR DESCRIPTION
**Pull request by jerryfreshworks**
- add GU_ID to userEntity
- add new migration to add GU_ID to user table
- rename a little bit on user.interceptor

### CODE REVIEW

**Review by michel-fresh — APPROVED** [review]
looks fine, are we using this anywhere?

**Comment by michel-fresh** [comment]
api test fails, you've probably seen: `null value in column "gu_id" violates not-null constraint`

**Comment by jerryfreshworks** [comment]
@michel-fresh good question... we didn't use gu_id  actually. I thought team want to save more user info for the future.

**Comment by michel-fresh** [comment]
> @michel-fresh good question... we didn't use gu_id actually. I thought team want to save more user info for the future.

I think the idea was to not use kc_id and use gu_id

**Comment by jerryfreshworks** [comment]
@michel-fresh ok, thanks for clarifying. Then I will fix the testing fail. and fix the place we use "kc_id" to query.

**Review by michel-fresh — APPROVED** [review]

**Pull request merged**
