### PR TITLE
Add endpoint for downloading interpreter data in excel sheet

### PR DESCRIPTION
**Pull request by arunrapolu4491**
Add endpoint for downloading interpreter data in excel sheet

### CODE REVIEW

**Comment by marzmehr** [comment]
This looks good, please make the following changes:

1. Change call to accepts ids of interpreters and only download those ids.
2. Remove columns "address_longitude" , "address_latitude",  "geo_service",  "disabled"
3. Change "crc_check_date" column format to "dd-MMM-YYYY" eg."23-Jun-2021"
4. Map "contract_valid" info: True=>"Yes" and False=>"No"
5. Map "completed_training" info: True=>"Yes" and False=>"No"

**Review by marzmehr — CHANGES_REQUESTED** [review]
Good job, it now works in swagger. But we're not able to use it in the front-end. As I've mentioned earlier today; please make changes such that the list of IDs are read from the body. 
A good example for you to follow is the '/api/v1/interpreter/search' call.

**Comment by arunrapolu4491** [comment]
> Good job, it now works in swagger. But we're not able to use it in the front-end. As I've mentioned earlier today; please make changes such that the list of IDs are read from the body. A good example for you to follow is the '/api/v1/interpreter/search' call.

Fixed the changes Please look into it @marzmehr

**Comment by marzmehr** [comment]
No longer applicable

**Pull request closed without merging**
