### PR TITLE
Csbiss 61 changelog

### PR DESCRIPTION
**Pull request by michel-fresh**
PRing this first leg of work to avoid a huge PR later

- event entities +, RO
- updates to booking and interpreter ROs

### CODE REVIEW

**Comment by michel-fresh** [comment]
@jerryfreshworks I think this is pretty close but I'm seeing this error when I run the dev server:
```
Error: Entity metadata for BookingEntity#events was not found. Check if you specified a correct entity object and if it's connected in the connection options.
```
and same for InterpreterEntity#events
do you see anything missing? can you try running this locally and see if same issue?

The error stops if I remove the @OneToMany relation declaration from the Event entity files.

**Comment by jerryfreshworks** [comment]
@michel-fresh  Great and fast work. Other than Entity error, all looks good. I left message at channel thread.

**Review by fwpushan — APPROVED** [review]

**Comment by fwpushan** [comment]
@michel-fresh Can you check why tests are failing ?

**Comment by michel-fresh** [comment]
@jerryfreshworks @fwpushan tests have passed! all good if we want to hold off on merging. opening new PR against this one.

**Pull request merged**
